
env:
  global:
    - DOCKER_NAME_TAG=ubuntu:18.04
    - DOCKER_PACKAGES="build-essential bsdmainutils curl git ca-certificates"

before_install: set -o errexit; source .travis/build_1_before_install.sh
install: set -o errexit; source .travis/build_linux_2_install.sh
before_script: set -o errexit; source .travis/build_linux_3_before_script.sh
script: if [ $SECONDS -gt 1200 ]; then set +o errexit; echo "Travis early exit to cache current state"; false; else set -o errexit; source .travis/build_linux_4_script.sh; fi

jobs:
  include:
    - os: linux
      dist: trusty
      language: cpp
      services: docker
      env:
      - HOST=x86_64-unknown-linux-gnu
      - PACKAGES="bash-completion debhelper libboost-chrono-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libboost-thread-dev libdbus-1-dev libminiupnpc-dev libdb++-dev libqrencode-dev libssl1.0-dev qt5-default qtbase5-dev qttools5-dev qttools5-dev-tools cmake ninja-build"
    - os: linux
      dist: trusty
      language: cpp
      services: docker
      env:
      - HOST="x86_64-w64-mingw32"
      - PACKAGES="g++-mingw-w64-x86-64 wget xz-utils cmake ninja-build zip"
    - os: linux
      dist: trusty
      language: cpp
      services: docker
      env:
      - HOST="i686-w64-mingw32"
      - PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev wget xz-utils cmake ninja-build zip"
    - os: osx
      osx_image: xcode10
      language: cpp
      install: set -o errexit; source .travis/build_macosx_2_install.sh
      before_script: set -o errexit; source .travis/build_macosx_3_before_script.sh
      script: if [ $SECONDS -gt 1200 ]; then set +o errexit; echo "Travis early exit to cache current state"; false; else set -o errexit; source .travis/build_macosx_4_script.sh; fi

notifications:
  slack:
    rooms:
      secure: kicq+PakRDw1En6D+PF5EEggzAEWCgANmrEmOfpWXwWtpXaFwL/2C7NuY1Ts5YJ2O/REqxtFcCqohGnL5zPo1pSDWUISFZLbJTkRygYb/2BREHbZh9FKIRCzHIcPfeHGE8eT6rytiSv9NVzMYQB8dhvSvTEUwScJc5IwllR+MP7JOkgGHUk8keoDbDa2Fz/zWLiR4pHgGRAZAlUYsON+6Pc1GXuPIbfDwid/2GxswWw0r9rtKXgRZDmJ76FWJzoazGJdJoLHthPzoeEs0B6kBt2FPJvz7H44kmJgR9x4MrOOMZIBO0jVsyqwcTqlplCodJvkPxg1Z1/nFCWOueErWnztrMKKzLvw5O9exi8kYATL68w6eprVbXhCJ1NCo82kQ1laFMv/jh9RwYtGku/k+Pct17MJwytX4bRvWSiIKUNh+YNxZgCM9jg1dgYUIOeFJenvYImKC23yeRUSCzZsCem/AIq4HRaLN4ZtD6xsaBj+IpFn2l5jy/v0vSWv+WiYb1Io+Rw1GWYvQ4DjCCqlQuyqimWCnitBuAn6fdQg5v8dFIc6A/9WMYFkuhlqlI04dm3MfTcM54v5G4t4v6t1XpsZW0AFriT0+poa0YHdGrM+EAAeyTEmqkiBGsyNP3Ocb/KB/i3kV0VEkDbEfXpSAGjcg88n+Q9T14zNzcL3p80=
